#!/bin/bash
# Usage: ./000-install-dependencies

# Extract installed bundles; append space to the end of each line.
installed_bundles=$(swupd bundle-list | grep '^ - ' | sed 's/$/ /g')

osrel=$(grep VERSION_ID /etc/os-release | cut -f2 -d=)
add_list=""
count=0

for bundle_name in \
    c-basic dev-utils nasm yasm sysadmin-basic devpkg-alsa-lib    \
    devpkg-appstream-glib devpkg-bzip2 devpkg-fontconfig          \
    devpkg-fribidi devpkg-freetype devpkg-gnutls devpkg-libass    \
    devpkg-libdrm devpkg-libgcrypt devpkg-libjpeg-turbo           \
    devpkg-libogg devpkg-librsvg devpkg-libtheora devpkg-libva    \
    devpkg-libvorbis devpkg-libvpx devpkg-libwebp devpkg-libX11   \
    devpkg-libxcb devpkg-libxml2 devpkg-libXvMC devpkg-mediasdk   \
    devpkg-mesa devpkg-numactl devpkg-opus devpkg-pulseaudio      \
    devpkg-SDL2 devpkg-SDL2_gfx devpkg-SDL2_image devpkg-SDL2_net \
    devpkg-SDL2_ttf devpkg-speex devpkg-v4l-utils devpkg-zlib     \
    curl unzip package-utils                                      \
;do
    if [[ ! ${installed_bundles} =~ " - ${bundle_name} " ]]; then
        add_list="${add_list} ${bundle_name}"
    else
        count=$(( ${count} + 1 ))
    fi
done

# Add bundle for building the NVIDIA NVDEC-enabled VA-API driver.
if [[ -f /opt/nvidia/bin/nvidia-settings ]]; then
    if [[ ! ${installed_bundles} =~ " - devpkg-gst-plugins-bad " ]]; then
        add_list="${add_list} devpkg-gst-plugins-bad"
    else
        count=$(( ${count} + 1 ))
    fi
fi

# Add devpkg-lcms2 bundle. FFmpeg 5.1 requires version 2.13+.
if [[ ! ${installed_bundles} =~ " - devpkg-lcms2 " ]]; then
    [[ $osrel -ge 36600 ]] && add_list="${add_list} devpkg-lcms2"
else
    count=$(( ${count} + 1 ))
fi

# Add devpkg-wavpack bundle.
if [[ ! ${installed_bundles} =~ " - devpkg-wavpack " ]]; then
    [[ $osrel -ge 35950 ]] && add_list="${add_list} devpkg-wavpack"
else
    count=$(( ${count} + 1 ))
fi

# Building FFmpeg with flags "--enable-vulkan --enable-libglslang"
# requires glslang and vulkan header files provided by developer-gpu.
# Add bundle optionally due to missing glslang headers in CL <= 35920.
if [[ ! ${installed_bundles} =~ " - developer-gpu " ]]; then
    [[ $osrel -ge 35730 ]] && add_list="${add_list} developer-gpu"
else
    count=$(( ${count} + 1 ))
fi

if [[ -n ${add_list} ]]; then
    add_list=${add_list## } # remove leading whitespace
    echo "swupd bundle-add ${add_list}"
    swupd bundle-add ${add_list}
    ldconfig
fi

# Add gcc10 if the NVIDIA CUDA Toolkit is present.
if [[ -f /usr/local/cuda/include/cuda.h ]]; then
    gccver=$( gcc --version | awk '{ printf("%.0f\n", $8); exit }' )
    if [[ $gccver -gt 10 ]]; then
        if [[ ! ${installed_bundles} =~ " - c-extras-gcc10 " ]]; then
            echo "swupd bundle-add c-extras-gcc10"
            swupd bundle-add c-extras-gcc10
        else
            count=$(( ${count} + 1 ))
        fi
    fi
fi

if [[ ${count} -gt 0 ]]; then
    echo "${count} bundles were already installed"
fi

